name: selenium_TestNG_Project

on: 
  push:
    branches:
      - main  # You can specify branches here, or remove if you want to trigger on all branches.

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest available Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Correct version of checkout action (v2 is stable)

      - name: Set up JDK 21
        uses: actions/setup-java@v2  # Correct version of setup-java action
        with:
          distribution: 'temurin'  # Using the Temurin distribution
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install  # Running Maven build
